### ISSUE TITLE
new color for pending 'ping' elements on /status

### ISSUE THREAD

**Issue by weddleben** [Nashville-Public-Library/booth#116]
on the `/status` page, for the 'ping' elements, we're changing the element color to yellow while it is being pinged. This is meant to signify that this is the hostname/IP currently being pinged, and we are waiting to see the result. But the current color is difficult to read! Change it to a darker yellow, or orange, or any other color that signifies that the result is pending. The main thing is that you can actually read it.

The JS loop that does the pinging will read the color set in the `status.html` file, so you just need to change it there and the JS will read that value when pinging.

![ss](https://github.com/user-attachments/assets/e896604d-e69f-4760-9f5e-8dc0fde01b44)

**Comment by weddleben** [comment]
@travis-humbert you up for tackling this one?

**Comment by travis-humbert** [comment]
You're right about that orange being too close to red! I think I've gone through and changed it and added a commit above... let me know if 

1) that color is better - it can easily be changed if not! and 
2) this was the right way of going about correcting a pull request.

Thanks for your patience Ben!

**Comment by weddleben** [comment]
keeping current color (for now).
