### ISSUE TITLE
add link to /booth/banner on homepage

### ISSUE THREAD

**Issue by weddleben** [Nashville-Public-Library/booth#119]
on the homepage, add a link to `/booth/banner`.

**Comment by weddleben** [comment]
@travis-humbert you feel like tackling this one?

**Comment by travis-humbert** [comment]
Yeah, I’d be glad to! It’ll be good practice remembering how this works.Thanks!- Travis Sent from my iPhoneOn Nov 12, 2024, at 1:44 PM, Ben Weddle ***@***.***> wrote:﻿
Assigned #119 to @travis-humbert.

**Comment by weddleben** [comment]
@travis-humbert excellent! PLEASE feel free to rearrange the formatting for all the links on the homepage. I'm not in love with any of that. So long as the links are there and it's clear what they are linking to...

**Comment by travis-humbert** [comment]
Quick question with this... when you say homepage, which do you mean? Typically I would think of the /booth/ page as the central, "home" base for everything, but I noticed there's a page listed in the repository called /home/ that appears to be what the /404/ page is extended off of. Is one of these what you were thinking of having the link posted on, or is it somewhere else?

Forgive my ignorance and any lack of proper terminology! And thanks again!

**Comment by weddleben** [comment]
ALSO, in case you're using an old local copy of this repository that you had on your computer, don't forget to run `git pull` before you start working/making commits! should've mentioned that before...

**Comment by weddleben** [comment]
amazing work! thank you!

Would love to change up the formatting though. I have no ideas. I just think it's ugly right now. Not sure if anyone actually uses the home page, but yeah, could be a fun project for you @travis-humbert

**Comment by weddleben** [comment]
excellent. could be a great way to learn more about how to work with HTML & CSS.
