### ISSUE TITLE
Update Dropdown Options on /booth/banner

### ISSUE THREAD

**Issue by weddleben** [Nashville-Public-Library/booth#125]
Since Tiffany is no longer here, [these options](https://github.com/Nashville-Public-Library/booth/blob/main/app/templates/banner.html) need to be updated...

**Comment by weddleben** [comment]
@travis-humbert could be a good one for you to tackle. Not a priority though...

**Comment by travis-humbert** [comment]
No problem! I went ahead and did a quick update (I'm still trying to absorb the process of it all) and uploaded it back with a pull request. Let me know of your thoughts and any changes/suggestions.

**Comment by weddleben** [comment]
done! Thank you to Travis!
